### PR TITLE
 Master - Selenium Survey agent tests

### PR DESCRIPTION
**Pull request by s7design**
Hello @carlosfrodriguez ,

Here are selenium test for following modules:

AgentSurveyAdd
AgentSurveyEdit
AgentSurveyOverview
AgentSurveryZoom

Tomorrow remaining ones will be completed and pushed.

Regards,
Sanjin

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Sanjin,

Than you for your pull request, I have some problems with it:

* The directory is not correct, test must be under the scripts/<b>test</b> directory, not directly under scripts

* Besides that some tests where the Survey is deleted fails into my system, please add waits before the delete dialog and after to prevent this issues.

<b>AgentSurveyEdit</b>
* not ok 86 - Survey test143814606963563873 - deleted

<b>AgentSurveyZoom</b>
* not ok 45 - Survey test1438146124752841099 - deleted

<b>AgentSurveyOverview</b>
* not ok 35 - Survey test1438146160330026479 - deleted

Please fix all this issues and update the pull request.

((enjoy))
cr.

**Comment by s7design** [comment]
Hello @carlosfrodriguez ,

Thank you for pointing out wrong directory, that was error from my side. Updated correct directory now.

In all these tests survey is deleted directly from DB, since there is no function to delete survey in backend, so there is no delete dialog. Not sure why it's not working out for you. In both firefox and phantomjs, tests perform as expected on my machine. 
There is one thing i noticed,AgentSurveyAdd seems to passed for you, and that's test that delete survey from DB looking at it's title. in other cases that failed for you, tests are deleted by there ID's.

Please if you can check it again and notify me on its status.

Regards,
Sanjin

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

I updated PR as we had spoken. I saw that there were some unneeded data (survey-queue) in DB after running the tests. They data are cleaned up with the last commit. 
I suppose all tests work now.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
hi @s7design, Sanjin, Zoran,

Thank you for the update it works great now :-), the pull request was merged in: https://github.com/OTRS/Survey/commit/03753bed91ede3b41c0dcb6b7101f15545bafdec

((enjoy))
cr

**Pull request closed without merging**
