### PR TITLE
Marked strings as translatable, Hungarian translation of sopm

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @mgruner 
I found some strings in this module, which were not marked as translatable. I added Hungarian translation for .sopm file.
Please sync translations with Transifex after commit!

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez and @mgruner 
Can you check this pull request?

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez and @mgruner 
Can you check this pull request? This is almost 5 months old.

**Comment by mgruner** [comment]
@dvuckovic can you handle this in the meantime, please?

**Comment by dvuckovic** [comment]
Merged in 633b5e5, new translation source has been synced with Transifex.
Thanks @urbalazs, sorry it took so long.

**Pull request closed without merging**
