### PR TITLE
Master - Survey update to modern input fields

### PR DESCRIPTION
**Pull request by s7design**
Hi @carlosfrodriguez 

I have made this PR with update to modern fields, there were not specific situation like there are in ITSM with fields in a table or dialog. I believe it could be updated. I saw today that there is some PR with update for theses modern fields. If we should some improvement here we will be able to do that.

I did not change dropdown in AgentSureyZoom for Change Status. It is similar to Move dropdown in TicketZoom. I see that this one in TicketZoom was not changed.
We can change it if it will be necessary. I wanted to make PR for it to be able to finish all tasks connected with Survey and that we can continue with porting to OM for other public package modules. 

Regards
Zoran

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran,

Thank you for your pull request,

I found an Issue, when you add a new question to a survey, the type of the question is a select control, if you click on it the options are places wrongly below the question and not below type.

Can you please contact Dusan to take a look on it?

((enjoy))
cr

**Comment by s7design** [comment]
Thanks @carlosfrodriguez 

I will contact Dusan. You are right, there was the problem but I think that Dusan and his team have solved it already. There is PR https://github.com/OTRS/otrs/pull/661 I tested with these fixes and the problem that you mentioned is solved. It works fine now.

We will be in a touch about this.

Regards
Zoran

**Comment by s7design** [comment]
HI @carlosfrodriguez 

I checked this PR as you suggested me by mail, regarding to double added Class mistake in FAQ.
Here is all well by me.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran

I finally merge this pull request in https://github.com/OTRS/Survey/commit/c8c4cb99b6310ad8ae19fe9efc2e90948572b092, as changes from Dusan fixes the issue with the wrong position of the list.

((enjoy))
cr

**Pull request closed without merging**
